import LessonLayout from '../components/LessonLayout'

export default function Profit1() {
  return (
    <LessonLayout
      number="139"
      title="Profit — Part 1"
      summary="18 profit concepts — gross, operating, net, EBITDA, EBIT, pre-tax, after-tax, contribution, product, service, customer, channel, geographic, segment, project, contract, recurring, and one-time profit."
    >
      <h2>Profit — Part 1</h2>

      <h2>1. Gross Profit</h2>
      <p>Amount remaining after subtracting the cost of goods sold (COGS) or directly attributable cost from revenue.</p>
      <p><strong>Gross Profit = Revenue − COGS</strong></p>
      <p><strong>Gross Margin = (Gross Profit ÷ Revenue) × 100</strong></p>
      <p>Example: ₱500,000 − ₱280,000 = ₱220,000 gross profit. Margin = 44%.</p>
      <p>Gross profit shows product/service economics; it is not final profit because operating expenses, financing, and taxes still apply.</p>

      <h2>2. Operating Profit</h2>
      <p>Profit remaining after subtracting operating expenses from gross profit.</p>
      <p><strong>Operating Profit = Gross Profit − Operating Expenses</strong></p>
      <p><strong>Operating Margin = (Operating Profit ÷ Revenue) × 100</strong></p>
      <p>Example: ₱220,000 − ₱140,000 = ₱80,000 operating profit. Margin = 16%.</p>

      <h2>3. Net Profit</h2>
      <p>Amount remaining after all applicable expenses are deducted.</p>
      <p><strong>Net Profit = Revenue − All Expenses</strong></p>
      <p><strong>Net Margin = (Net Profit ÷ Revenue) × 100</strong></p>
      <p>Revenue is not profit. A business can have large revenue with little or no net profit.</p>

      <h2>4. EBITDA</h2>
      <p>Earnings Before Interest, Taxes, Depreciation, and Amortization.</p>
      <p><strong>EBITDA = EBIT + Depreciation + Amortization</strong></p>
      <p>Useful for comparing businesses with different debt, tax, and asset structures. EBITDA is not cash flow and not net profit.</p>

      <h2>5. EBIT</h2>
      <p>Earnings Before Interest and Taxes.</p>
      <p><strong>EBIT = Net Profit + Interest + Taxes</strong></p>
      <p><strong>EBIT = EBITDA − Depreciation − Amortization</strong></p>

      <h2>6. Pre-Tax Profit</h2>
      <p>Profit before income taxes.</p>
      <p><strong>Pre-Tax Profit = EBIT − Interest ± Other Non-Operating Items</strong></p>
      <p>Example: ₱100,000 − ₱15,000 + ₱5,000 = ₱90,000.</p>

      <h2>7. After-Tax Profit</h2>
      <p>Profit after income taxes.</p>
      <p><strong>After-Tax Profit = Pre-Tax Profit − Income Tax Expense</strong></p>
      <p>Example: ₱90,000 − ₱18,000 = ₱72,000.</p>

      <h2>8. Contribution Profit</h2>
      <p>Amount remaining after subtracting variable costs from revenue.</p>
      <p><strong>Contribution Profit = Revenue − Variable Costs</strong></p>
      <p><strong>Contribution Margin = (Contribution Profit ÷ Revenue) × 100</strong></p>
      <p><strong>Break-Even Revenue = Fixed Costs ÷ Contribution Margin</strong></p>

      <h2>9. Product Profit</h2>
      <p>Profit generated by a particular product.</p>
      <p><strong>Product Profit = Product Revenue − Product-Attributable Costs</strong></p>
      <p>Product revenue alone does not tell you whether a product is economically attractive.</p>

      <h2>10. Service Profit</h2>
      <p>Profitability of delivering a specific service.</p>
      <p><strong>Service Profit = Service Revenue − Direct Service Costs − Allocated Relevant Costs</strong></p>
      <p>Effective hourly profit = Service profit ÷ hours worked.</p>

      <h2>11. Customer Profit</h2>
      <p>Economic contribution generated by a particular customer after relevant costs.</p>
      <p><strong>Customer Profit = Customer Revenue − Customer-Attributable Costs</strong></p>
      <p>High revenue does not automatically mean high customer profitability.</p>

      <h2>12. Channel Profit</h2>
      <p>Profitability of a specific sales or distribution channel.</p>
      <p><strong>Channel Profit = Channel Revenue − Channel-Attributable Costs</strong></p>
      <p>Measure channels by contribution and profit, not revenue alone.</p>

      <h2>13. Geographic Profit</h2>
      <p>Profitability generated by a specific geographic market.</p>
      <p><strong>Geographic Profit = Geographic Revenue − Geographic Costs</strong></p>
      <p>Relevant costs include shipping, warehousing, local advertising, taxes, and delivery.</p>

      <h2>14. Segment Profit</h2>
      <p>Profitability by customer or business segment.</p>
      <p><strong>Segment Profit = Segment Revenue − Segment-Attributable Costs</strong></p>

      <h2>15. Project Profit</h2>
      <p>Profit generated by a specific project after its costs.</p>
      <p><strong>Project Profit = Project Revenue − Project Costs</strong></p>
      <p>Track throughout the project, not only at the end.</p>

      <h2>16. Contract Profit</h2>
      <p>Profit from a specific contract over its scope or period.</p>
      <p>A large contract can still be unattractive if it consumes disproportionate resources.</p>

      <h2>17. Recurring Profit</h2>
      <p>Profit from repeatable revenue streams like subscriptions, retainers, or maintenance.</p>
      <p>Recurring revenue does not automatically mean recurring profit. If recurring costs grow faster than recurring revenue, profitability declines.</p>

      <h2>18. One-Time Profit</h2>
      <p>Profit from transactions not expected to repeat regularly.</p>
      <p>One-time sales can generate cash while recurring revenue develops, but their economics and risks should be evaluated separately.</p>

      <hr />

      <h2>Profit Hierarchy</h2>
      <pre>{`Revenue
   ↓
− Direct Product/Service Costs
   ↓
GROSS PROFIT
   ↓
− Operating Expenses
   ↓
OPERATING PROFIT / EBIT
   ↓
± Non-Operating Items
   ↓
PRE-TAX PROFIT
   ↓
− Taxes
   ↓
NET / AFTER-TAX PROFIT`}</pre>

      <h2>Key Principles</h2>
      <ol>
        <li>Gross profit measures revenue remaining after direct product/service costs.</li>
        <li>Operating profit measures profitability after normal operating expenses.</li>
        <li>Net profit represents profit after applicable expenses and taxes.</li>
        <li>EBITDA excludes interest, taxes, depreciation, and amortization.</li>
        <li>EBIT represents earnings before interest and taxes.</li>
        <li>Pre-tax profit measures profit before income taxes.</li>
        <li>After-tax profit measures profit after income taxes.</li>
        <li>Contribution profit measures revenue remaining after variable costs.</li>
        <li>Profit should be analyzed at multiple levels, not only company-wide.</li>
        <li>High-revenue products, customers, channels, or regions are not necessarily the most profitable.</li>
        <li>Profit does not automatically equal cash flow.</li>
        <li>EBITDA is not cash flow.</li>
        <li>A sustainable business considers profitability together with liquidity, growth, risk, and customer value.</li>
      </ol>

      <h3>Core Formula</h3>
      <p>
        Revenue → Direct Costs → Gross Profit → Contribution → Operating Expenses → Operating
        Profit / EBIT → Financing &amp; Other Items → Pre-Tax Profit → Taxes → Net Profit →
        Multidimensional Profit Analysis → Optimization → Reinvestment → Sustainable Growth.
      </p>
    </LessonLayout>
  )
}
