import LessonLayout from '../components/LessonLayout'

export default function Roi3() {
  return (
    <LessonLayout
      number="193"
      title="ROI — Part 3"
      summary="11 infrastructure and return-form categories — infrastructure, expansion, geographic, revenue, profit, cash, gross, net, and annualized return, payback period, break-even period, and investment period."
    >
      <h2>ROI — Part 3</h2>

      <h2>Infrastructure ROI</h2>
      <p>Measures return from infrastructure investment.</p>
      <p>Examples: servers, networks, warehouses, facilities, and cloud infrastructure.</p>

      <h2>Expansion ROI</h2>
      <p>Measures financial return from entering a new market/location/capacity level.</p>

      <h2>Geographic ROI</h2>
      <p>Measures economic return associated with a specific location or geographic market.</p>

      <h2>Revenue Return</h2>
      <p>Return measured using generated revenue.</p>
      <p><strong>Revenue Return = Revenue Attributable to Investment</strong></p>
      <p>Revenue is not the same as profit.</p>

      <h2>Profit Return</h2>
      <p>Return measured using profit or contribution. This is often more useful than revenue alone when evaluating profitability.</p>

      <h2>Cash Return</h2>
      <p>Measures actual cash generated by an investment.</p>

      <h2>Gross Return</h2>
      <p>Return before selected operating/financing/tax deductions.</p>

      <h2>Net Return</h2>
      <p>Return after the costs included in the chosen definition.</p>

      <h2>Annualized Return</h2>
      <p>Converts a return over a period into an annualized rate.</p>
      <p><strong>Annualized Return = (Ending Value ÷ Beginning Value)^(1/n) − 1</strong></p>
      <p>where n is the number of years.</p>

      <h2>Payback Period</h2>
      <p>Time required to recover the initial investment through specified cash benefits.</p>
      <p><strong>Payback Period = Initial Investment ÷ Annual Cash Benefit</strong></p>

      <h2>Break-Even Period</h2>
      <p>Time required for cumulative contribution/benefits to cover the relevant investment or fixed cost.</p>

      <h2>Investment Period</h2>
      <p>The length of time capital remains committed to an investment.</p>

      <h3>ROI Timeline</h3>
      <pre>{`Investment
   ↓
Development / Implementation
   ↓
Launch
   ↓
Revenue / Savings
   ↓
Cumulative Benefits
   ↓
Break-Even
   ↓
Payback
   ↓
Net Return`}</pre>
    </LessonLayout>
  )
}
