import LessonLayout from '../components/LessonLayout'

export default function Roi2() {
  return (
    <LessonLayout
      number="192"
      title="ROI — Part 2"
      summary="11 digital and campaign ROI categories — website, SEO, social-media, content, influencer, email, event, partnership, sponsorship, software, automation, and AI ROI."
    >
      <h2>ROI — Part 2</h2>

      <h2>Website ROI</h2>
      <p>Evaluates whether website investment generates sufficient measurable benefits.</p>
      <p>Possible returns: sales, leads, bookings, lower support costs, and improved conversion.</p>

      <h2>SEO ROI</h2>
      <p>Measures financial benefits attributable to search-engine optimization relative to SEO investment.</p>

      <h2>Social-Media ROI</h2>
      <p>Evaluates business results from social-media activity.</p>
      <p>Possible returns: sales, leads, customer acquisition, retention, and brand outcomes.</p>

      <h2>Content ROI</h2>
      <p>Measures benefits generated by content relative to production/distribution costs.</p>

      <h2>Influencer ROI</h2>
      <p>Compares attributable return from an influencer partnership against campaign cost.</p>

      <h2>Email ROI</h2>
      <p>Measures revenue or contribution attributable to email campaigns relative to relevant costs.</p>

      <h2>Event ROI</h2>
      <p>Measures event-generated return against: venue, staff, marketing, equipment, logistics, and sponsorship costs.</p>

      <h2>Partnership ROI</h2>
      <p>Evaluates economic results generated by a partnership.</p>

      <h2>Sponsorship ROI</h2>
      <p>Measures return associated with sponsorship expenditure.</p>

      <h2>Software ROI</h2>
      <p>Measures benefits from software relative to acquisition, implementation, subscription, training, and maintenance costs.</p>

      <h2>Automation ROI</h2>
      <p>Measures financial benefits from automation.</p>
      <p>Example: Automation costs ₱100,000. Annual labor/time savings and additional contribution = ₱180,000. Simplified first-year net benefit: ₱80,000. Simplified ROI: 80%.</p>

      <h2>AI ROI</h2>
      <p>Evaluates economic benefits produced by AI relative to: software costs, API costs, infrastructure, integration, training, monitoring, human review, and maintenance.</p>
      <p>AI ROI should include quality and risk effects, not only labor savings.</p>
    </LessonLayout>
  )
}
