import LessonLayout from '../components/LessonLayout'

export default function Roi4() {
  return (
    <LessonLayout
      number="194"
      title="ROI — Part 4"
      summary="13 ROI analysis and measurement categories — return percentage, cost-benefit analysis, benefit-cost ratio, forecasting, measurement, tracking, comparison, benchmarking, attribution, incremental and marginal ROI, and short and long-term ROI."
    >
      <h2>ROI — Part 4</h2>

      <h2>Return Percentage</h2>
      <p>Expresses return relative to investment.</p>
      <p><strong>Return % = Net Benefit ÷ Investment × 100</strong></p>

      <h2>Cost-Benefit Analysis</h2>
      <p>Compares expected costs with expected benefits.</p>
      <p>Consider: initial costs, recurring costs, revenue, savings, risk, opportunity cost, and time.</p>

      <h2>Benefit-Cost Ratio</h2>
      <p><strong>BCR = Present Value of Benefits ÷ Present Value of Costs</strong></p>
      <p>A ratio above 1 indicates benefits exceed costs under the assumptions and valuation method used.</p>

      <h2>ROI Forecasting</h2>
      <p>Estimate future returns before investing.</p>

      <h2>ROI Measurement</h2>
      <p>Calculate actual returns after implementation.</p>

      <h2>ROI Tracking</h2>
      <p>Monitor returns continuously over time.</p>

      <h2>ROI Comparison</h2>
      <p>Compare alternatives using consistent assumptions.</p>

      <h2>ROI Benchmarking</h2>
      <p>Compare results with: internal historical performance, business targets, industry benchmarks, and comparable investments.</p>
      <p>Benchmarks must be comparable in scope, time period, accounting, and risk.</p>

      <h2>ROI Attribution</h2>
      <p>Determines which activity contributed to the observed result. Attribution is especially difficult when multiple marketing or sales channels affect the same customer.</p>

      <h2>Incremental ROI</h2>
      <p>Measures the return generated by an additional investment relative to the incremental cost.</p>

      <h2>Marginal ROI</h2>
      <p>Measures the return associated with an additional unit of investment.</p>

      <h2>Short-Term ROI</h2>
      <p>Focuses on near-term returns.</p>

      <h2>Long-Term ROI</h2>
      <p>Includes benefits and costs occurring over a longer period.</p>

      <h3>Important Principle</h3>
      <p>A high short-term ROI does not automatically mean an investment has the highest long-term economic value.</p>
    </LessonLayout>
  )
}
