import LessonLayout from '../components/LessonLayout'

export default function Roi1() {
  return (
    <LessonLayout
      number="191"
      title="ROI — Part 1"
      summary="15 ROI categories — return on investment, marketing, advertising, sales, product, project, technology, employee, training, equipment, asset, capital, customer, customer-acquisition, and customer-retention ROI."
    >
      <h2>ROI — Part 1</h2>

      <h2>Return on Investment</h2>
      <p>ROI measures the return generated relative to investment cost.</p>
      <p><strong>ROI = (Return − Investment Cost) ÷ Investment Cost × 100</strong></p>
      <p>Example: Investment = ₱100,000; Net gain = ₱30,000; ROI = 30%.</p>
      <p>ROI definitions must clearly specify which costs and benefits are included.</p>

      <h2>Marketing ROI</h2>
      <p>Measures financial return associated with marketing spending.</p>

      <h2>Advertising ROI</h2>
      <p>Evaluates return generated from advertising investment.</p>

      <h2>Sales ROI</h2>
      <p>Evaluates return from sales-related resources and expenditure.</p>

      <h2>Product ROI</h2>
      <p>Measures financial return associated with developing or launching a product.</p>

      <h2>Project ROI</h2>
      <p>Measures return generated by a project relative to project investment/cost.</p>

      <h2>Technology ROI</h2>
      <p>Measures financial benefits generated from technology investment.</p>

      <h2>Employee ROI</h2>
      <p>Examines the economic contribution associated with employee-related costs. It should not be interpreted as a complete measure of employee value.</p>

      <h2>Training ROI</h2>
      <p>Measures financial benefits associated with training compared with training costs.</p>

      <h2>Equipment ROI</h2>
      <p>Measures economic return generated by equipment relative to investment.</p>

      <h2>Asset ROI</h2>
      <p>Measures return associated with an asset or asset base.</p>

      <h2>Capital ROI</h2>
      <p>Evaluates return generated by capital invested in the business.</p>

      <h2>Customer ROI</h2>
      <p>Measures economic return from resources invested in serving/acquiring a customer.</p>

      <h2>Customer-Acquisition ROI</h2>
      <p>Compares customer contribution or other defined return with acquisition expenditure.</p>

      <h2>Customer-Retention ROI</h2>
      <p>Measures the return generated by retention investments.</p>

      <h3>ROI Architecture</h3>
      <pre>{`Investment
    ↓
Activity
    ↓
Customer / Operational Outcome
    ↓
Revenue / Savings
    ↓
Relevant Costs
    ↓
Net Benefit
    ↓
ROI`}</pre>
    </LessonLayout>
  )
}
