import LessonLayout from '../components/LessonLayout'

export default function Roi6() {
  return (
    <LessonLayout
      number="196"
      title="ROI — Part 6"
      summary="12 process, operational, and efficiency ROI categories — process, operational, efficiency, productivity, cost-saving, revenue-growth, margin, capital-efficiency, asset-utilization, inventory, working-capital, and GMROI."
    >
      <h2>ROI — Part 6</h2>

      <h2>Process ROI</h2>
      <p>Return from improving a business process.</p>
      <p>Example: Automation investment = ₱200,000; Annual savings = ₱300,000; Net annual benefit: ₱100,000.</p>

      <h2>Operational ROI</h2>
      <p>Return from operational improvements.</p>

      <h2>Efficiency ROI</h2>
      <p>Financial benefit from using fewer resources for the same output.</p>

      <h2>Productivity ROI</h2>
      <p>Return from increased output per unit of input.</p>

      <h2>Cost-Saving ROI</h2>
      <p>Measures savings generated from an investment.</p>

      <h2>Revenue-Growth ROI</h2>
      <p>Measures incremental revenue or contribution generated by growth investment.</p>

      <h2>Margin ROI</h2>
      <p>Evaluates investments based on their incremental contribution to margins.</p>

      <h2>Capital-Efficiency ROI</h2>
      <p>Evaluates how effectively invested capital generates returns.</p>

      <h2>Asset-Utilization ROI</h2>
      <p>Examines return generated relative to the use of assets.</p>

      <h2>Inventory ROI</h2>
      <p>Evaluates the return generated from inventory investment.</p>
      <p><strong>GMROI = Gross Margin Dollars ÷ Average Inventory Cost</strong></p>
      <p>Example: Gross margin = ₱500,000; Average inventory cost = ₱250,000; GMROI = 2.0. Meaning each ₱1 of average inventory cost generated ₱2 of gross-margin dollars during the measurement period.</p>

      <h2>Working-Capital ROI</h2>
      <p>Measures economic return relative to capital tied up in receivables, inventory, and other working-capital resources.</p>
    </LessonLayout>
  )
}
