import LessonLayout from '../components/LessonLayout'

export default function Roi8() {
  return (
    <LessonLayout
      number="198"
      title="ROI — Part 8"
      summary="11 ROI decision and management categories — sales-pipeline ROI, investment hurdle rate, ROI target and threshold, ROI dashboard, reporting, optimization, decision-making, and return-on-capital analysis."
    >
      <h2>ROI — Part 8</h2>

      <h2>Sales-Pipeline ROI</h2>
      <p>Measures return associated with resources invested in creating and managing sales opportunities.</p>

      <h2>Investment Hurdle Rate</h2>
      <p>The minimum return required for an investment to be considered acceptable under a company's decision framework.</p>

      <h2>ROI Target</h2>
      <p>The return level the organization intends to achieve.</p>

      <h2>ROI Threshold</h2>
      <p>The minimum ROI at which a project or investment remains economically acceptable under defined assumptions.</p>

      <h2>ROI Dashboard</h2>
      <p>A dashboard may contain: investment, revenue return, contribution, net benefit, ROI %, payback, risk, and actual vs forecast.</p>

      <h2>ROI Reporting</h2>
      <p>Communicating investment performance to decision-makers.</p>
      <p>A good report separates: Actual → Forecast → Variance → Cause → Action.</p>

      <h2>ROI Optimization</h2>
      <p>Improving return by changing: cost, price, conversion, retention, productivity, utilization, and investment allocation.</p>

      <h2>ROI Decision-Making</h2>
      <p>Use ROI alongside: strategic fit, risk, liquidity, capacity, opportunity cost, customer impact, and compliance.</p>
      <p>ROI should not be the only decision criterion.</p>

      <h2>Return-on-Capital Analysis</h2>
      <p>Evaluates the return generated by capital deployed in the business.</p>
      <p><strong>ROIC = NOPAT ÷ Average Invested Capital</strong></p>
      <p>where NOPAT means net operating profit after tax under the relevant calculation methodology.</p>
    </LessonLayout>
  )
}
